In [1]:
import numpy as np

def print_graph(intMatrix):
    print (intMatrix)

def create_graph (matrix, hasCost, num_edges,directed):
    i = 0
    while i < num_edges :
        u = int(input('u: '))
        v = int(input('v: '))
        if hasCost == True :
            cost = int(input('Cost / weight: '))
        else:
            cost = 1
        matrix[(u-1)][(v-1)] = cost;
        if directed == False:
            matrix[(v-1)][u-1] = cost;
        i += 1


def main():
    print("Numero de nodos")
    num_nodes = int(input())
    print("Tiene costo?")
    hasCost = int(input())
    print("Esta dirigido?")
    directed = int(input())
    directed = True if (directed == 1) else False 
    hasCost = True if (hasCost == 1) else False
    print("Número de ejes?")
    num_edges = int(input())
    matrix = np.zeros((num_nodes, num_nodes))
    create_graph(matrix,hasCost,num_edges,directed)
    print_graph(matrix)

main()

Numero de nodos
4
Tiene costo?
0
Esta dirigido?
0
Número de ejes?
5
u: 1
v: 2
u: 2
v: 3
u: 3
v: 4
u: 4
v: 1
u: 1
v: 3
[[0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [1. 0. 1. 0.]]
